name: flutter_app
description: NTUST Life TAT, convenient, concise, fast, powerful, enrich your NTUST life!

# you can use this command to build both android app bundle and ios ipa:
# flutter clean && flutter build ios --split-debug-info=build/app/outputs/symbols --obfuscate && flutter build appbundle --split-debug-info=build/app/outputs/symbols --obfuscate --shrink
# follow the google play new policy in 2021, do not build apk but aab.
# CHECK THE BUILD CODE BEFORE DISTRIBUTION!!
version: 1.3.8+61

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path: ^1.8.1
  provider: ^6.0.3
  path_provider: ^2.0.11
  quiver: ^3.1.0
  url_launcher: ^6.1.5
  #開啟email phone url...
  logger: ^1.1.0
  #顯示Log
  sprintf: ^6.0.0
  flutter_local_notifications: ^9.7.0
  #通知欄  需修改android原始碼
  rxdart: ^0.27.5
  #通知欄有使用到
  android_intent: ^2.0.2
  device_info: ^2.0.3
  html_unescape: ^2.0.0
  #處理HTML特殊字
  local_auth: ^2.1.1
  #驗證身分指紋
  version: ^2.0.0
  #版本比較
  file_picker: ^4.6.1
  #選擇android資料夾
  #----------store data----------#
  shared_preferences: ^2.0.15
  flutter_cache_manager: ^3.3.0
  #----------internet----------#
  dio: ^4.0.6
  #網路get post API
  dio_cookie_manager: ^2.0.0
  #用於產生cookie_jar與dio接口
  cookie_jar: ^3.0.1
  #可儲存式cookies
  html: ^0.15.0
  #html解析器
  connectivity: ^3.0.6
  clipboard: ^0.1.3
  #剪貼簿
  #----------WebView----------#
  flutter_inappwebview: ^5.4.3+7
  webview_flutter: ^3.0.4
  #---------icon----------#
  eva_icons_flutter: ^3.1.0
  #https://akveo.github.io/eva-icons/#/
  fluttericon: ^2.0.0
  #https://oblador.github.io/react-native-vector-icons/
  #---------json----------#
  json_annotation: ^4.6.0
  #----------other----------#
  back_button_interceptor: ^6.0.1
  #攔截返回鍵訊息
  intl: ^0.17.0
  #DateTime to String
  package_info: ^2.0.2
  #檢測app版本用於檢查更新
  #----------html viewer----------#
  #flutter_html: ^2.2.1
  flutter_widget_from_html: ^0.8.5
  #----------animation----------#
  flutter_staggered_animations: ^1.0.0
  #listView or gridView動畫
  #----------download----------#
  flutter_downloader: ^1.8.1
  #下載app更新
  open_file: ^3.2.1
  permission_handler: ^10.0.0
  mime_type: ^1.0.0
  github: ^9.4.0
  #----------Widget----------#
  get: ^4.6.5
  bot_toast: ^4.0.3
  #提供ListView可下拉式更新並且可動態加載
  cached_network_image: ^3.2.1
  #用url顯示圖片
  auto_size_text: ^3.0.0
  #課表顯示有用到
  table_calendar: ^3.0.6
  #顯示行事曆
  expansion_tile_card: ^2.0.0
  fluttertoast: ^8.0.9
  #Toast
  awesome_dialog: ^2.2.1
  #顯示Error時用到
  flutter_slidable: ^2.0.0
  #email使用可左右滑抽屜
  flutter_spinkit: ^5.1.0
  #等待動畫
  flutter_markdown: ^0.6.10+3
  numberpicker: ^2.1.1
  #選擇學期
  alice_lightweight: ^3.1.0
  pretty_json: ^2.0.0
  icalendar_parser: ^1.0.2
  charset_converter: ^2.1.0

  # Firebase
  firebase_core: ^1.20.0
  firebase_analytics: ^9.3.0
  firebase_crashlytics: ^2.8.6
  firebase_remote_config: ^2.0.13
  firebase_messaging: ^12.0.1
  google_mobile_ads: ^2.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  #flutter pub run flutter_launcher_icons:main -f pubspec.yaml
  #利用以下的flutter_icons設定icon位置
  flutter_native_splash: ^2.2.3+1
  #flutter pub run flutter_native_splash:create
  #---------json----------#
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/

fonts:
  - family: MyIcon
    fonts:
      - asset: assets/fonts/MyIcon.ttf
  - family: MyFont
    fonts:
      - asset: fonts/GenSenRounded-R.ttc
        weight: 400
      - asset: fonts/GenSenRounded-B.ttc
        weight: 700

flutter_intl:
  enabled: true

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/ios-icon.png"
  image_path_android: "assets/launcher/android-icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/splash.png