allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    afterEvaluate {
        android {
            compileSdkVersion 36

            if (project.plugins.hasPlugin("com.android.library") || project.plugins.hasPlugin("com.android.application")) {
                tasks.withType(JavaCompile) {
                    options.compilerArgs.remove("-Werror")
                    options.compilerArgs.remove("-Xlint:all")
                    options.compilerArgs << "-Xlint:-options"
                }
            }
        }
    }
}

subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
